services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    depends_on:
      - mongodb
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017

  backend:
    image: maurii9070/hia-backend-final:latest
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/app-salon
    volumes:
      - ../hia-backend-node/.env:/app/.env
    command: sh -c "npm run seed:import && npm run dev"

  frontend:
    image: maurii9070/hia-frontend-test:latest
    ports:
      - "3000:3000"
    volumes:
      - ../hia-frontend-vuejs/.env.local:/app/.env.local

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=30 # Intervalo en segundos para verificar actualizaciones
volumes:
  mongodb_data:
